### ISSUE TITLE
qual a versão que precisa para usar este?

### ISSUE THREAD

**Issue by DFN-master** [CitraIT/ZabbixGLPI#1]
eu tenho o ambiente com o zabbix 6.2 e GLPI 10.0.10, porem não funcionou pois no GPLPI 10.0.10 o app_token é obrigatório e o script não permite acesso usando o app_token pois esse recurso se tornou obrigatório depois da versão do GLPI 10.0.2. 
neste ocorre o mesmo problema?

**Comment by CitraIT** [comment]
Olá DNF-master. tudo bem?
Usamos o zabbix 6.4 e glpi 10.0.8. 
Mas, o script foi desenvolvido de forma a  usar o app_token. 
Por gentileza, veja o PDF que foi anexado a este repositório (na data deste comentário). É um e-book de zabbix e contém o passo-a-passo para a integração. Lá eu falo do app_token, como gerá-lo e configurar todo o processo da notificação.

Atte.,
~luciano

**Comment by DFN-master** [comment]
Perfeito, vou rever as config aqui

Em ter., 23 de jan. de 2024 10:26, Citra IT - Excelência em TI <
***@***.***> escreveu:
